# Generated by Django 4.2 on 2023-04-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('subject', models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('social', 'Social Studies'), ('english', 'English')], default='math')),
                ('topic', models.CharField()),
                ('classs', models.CharField()),
                ('comments', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('answer', models.CharField()),
                ('image', models.CharField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardify_api.deck')),
            ],
        ),
    ]
