# Generated by Django 4.2 on 2023-04-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardify_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
    ]
